services:
  chrome:
    image: kasmweb/chrome:1.16.0     
    container_name: chrome
    environment:
      - VNC_PW=${CHROME_PASSWORD}
      - VNC_USER=${CHROME_USER}
      - KASM_PORT=${CHROME_PORT} # Internal app listening port
    ports:
      - "${CHROME_PORT}:${CHROME_PORT}" # Map Host:Container ports
    shm_size: 1gb 

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    environment:
      # The token used to access the /admin page
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      # Optional: Disable new signups once you have created your account
      - SIGNUPS_ALLOWED=true 
    ports:
      - "${VAULTWARDEN_PORT}:${VAULTWARDEN_PORT}"
        
  gemini:
    build:
      context: .
      dockerfile: Dockerfile.gemini
    volumes:
      - ${HOME}/Coding:/Coding
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
