services:
  chrome:
    image: kasmweb/chrome:1.16.0     
    container_name: chrome
    environment:
      - VNC_PW=${CHROME_PASSWORD}
      - VNC_USER=${CHROME_USER}
      - KASM_PORT=${CHROME_PORT} # Internal app listening port
    ports:
      - "${CHROME_PORT}:${CHROME_PORT}" # Map Host:Container ports
    shm_size: 1gb 
        
  gemini:
    build:
      context: .
      dockerfile: Dockerfile.gemini
    volumes:
      - ${HOME}/Coding:/Coding
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
